// Omnivest - all mocked data (frontend only)

export const brokers = [
  { name: 'Zerodha', logo: 'ZR' },
  { name: 'Groww', logo: 'GR' },
  { name: 'Upstox', logo: 'UP' },
  { name: 'Angel One', logo: 'AO' },
  { name: 'ICICI Direct', logo: 'IC' },
  { name: '5paisa', logo: '5P' },
  { name: 'HDFC Sky', logo: 'HD' },
  { name: 'Dhan', logo: 'DH' },
  { name: 'Kotak', logo: 'KO' },
  { name: 'Axis Direct', logo: 'AX' },
];

export const trustStats = [
  { value: '₹42,000 Cr+', label: 'Invested via baskets' },
  { value: '18 Lakh+', label: 'Active investors' },
  { value: '550+', label: 'Curated baskets' },
  { value: '4.6★', label: 'Average app rating' },
];

export const strategies = [
  { key: 'asset-allocation', label: 'Asset allocation', icon: 'Cloud' },
  { key: 'model-based', label: 'Model based', icon: 'BarChart3' },
  { key: 'sectoral', label: 'Sectoral', icon: 'Building2' },
  { key: 'thematic', label: 'Thematic', icon: 'Zap' },
  { key: 'smart-beta', label: 'Smart beta', icon: 'Sigma' },
  { key: 'index', label: 'Index / Passive', icon: 'LineChart' },
];

export const managers = [
  { id: 'windmill', name: 'Windmill Capital', logo: 'WC', sebiReg: 'INA000012345', philosophy: 'Rules-based quantitative investing', description: 'A quantitative research house focused on model-driven baskets.', subscribers: '2.4L', baskets: 12 },
  { id: 'northstar', name: 'Northstar Research', logo: 'NR', sebiReg: 'INA000023456', philosophy: 'Long-term compounding with quality businesses', description: 'Fundamental research team focused on Indian equities.', subscribers: '1.1L', baskets: 8 },
  { id: 'wright', name: 'Wright Research', logo: 'WR', sebiReg: 'INA000034567', philosophy: 'Data-driven momentum & factor investing', description: 'AI-first research team.', subscribers: '82K', baskets: 6 },
  { id: 'niveshaay', name: 'Niveshaay', logo: 'NV', sebiReg: 'INA000045678', philosophy: 'Small-cap and emerging themes', description: 'Focus on structural growth and MSME themes.', subscribers: '54K', baskets: 5 },
  { id: 'weekend', name: 'Weekend Investing', logo: 'WI', sebiReg: 'INA000056789', philosophy: 'Momentum + weekly rebalance', description: 'Weekly rules-based momentum strategies.', subscribers: '96K', baskets: 4 },
  { id: 'omniscience', name: 'Omniscience Capital', logo: 'OC', sebiReg: 'INA000067890', philosophy: 'Scientific investing', description: 'Global scientific investing.', subscribers: '31K', baskets: 3 },
];

const makeReturns = (m1, m6, y1, y3, y5, cagr) => ({ m1, m6, y1, y3, y5, cagr });

export const baskets = [
  {
    id: 'all-weather',
    name: 'All Weather Portfolio',
    subtitle: 'A steady multi-asset mix that weathers market cycles',
    managerId: 'windmill',
    volatility: 'Low',
    risk: 'Low',
    strategy: 'asset-allocation',
    themes: ['Multi-asset'],
    sectors: [],
    goals: ['Wealth creation', 'Retirement'],
    assetType: 'Multi-asset',
    returns: makeReturns(1.2, 6.4, 12.8, 18.4, 15.2, 14.6),
    minAmount: 8500,
    horizon: 'Long term (5y+)',
    rebalanceFreq: 'Quarterly',
    lastRebalancedAt: '2025-06-12',
    fee: { type: 'free', amount: 0, cycle: null },
    subscription: 'Free',
    constituents: [
      { symbol: 'NIFTYBEES', name: 'Nifty BeES', weight: 34, type: 'ETF' },
      { symbol: 'LIQUIDBEES', name: 'Liquid BeES', weight: 28, type: 'ETF' },
      { symbol: 'GOLDBEES', name: 'Gold BeES', weight: 22, type: 'ETF' },
      { symbol: 'MAFANG', name: 'Motilal NASDAQ 100 ETF', weight: 16, type: 'ETF' },
    ],
    methodology: 'A four-way asset allocation across Indian equity, debt, gold, and international equity. Rebalanced quarterly to maintain target weights.',
    published: true,
  },
  {
    id: 'momentum-movers',
    name: 'Momentum Movers',
    subtitle: 'Ride the strongest trending large & mid caps',
    managerId: 'wright',
    volatility: 'High', risk: 'High', strategy: 'model-based',
    themes: ['Momentum'], sectors: [], goals: ['Wealth creation'], assetType: 'Equity',
    returns: makeReturns(3.4, 14.2, 28.5, 31.2, 26.8, 24.9),
    minAmount: 12000, horizon: 'Medium term (3-5y)', rebalanceFreq: 'Monthly',
    lastRebalancedAt: '2025-07-01', fee: { type: 'subscription', amount: 199, cycle: 'monthly' }, subscription: 'Paid',
    constituents: [
      { symbol: 'ADANIENT', name: 'Adani Enterprises', weight: 12, type: 'Stock' },
      { symbol: 'BAJFINANCE', name: 'Bajaj Finance', weight: 10, type: 'Stock' },
      { symbol: 'BEL', name: 'Bharat Electronics', weight: 10, type: 'Stock' },
      { symbol: 'HAL', name: 'Hindustan Aeronautics', weight: 9, type: 'Stock' },
      { symbol: 'TATAMOTORS', name: 'Tata Motors', weight: 9, type: 'Stock' },
      { symbol: 'TITAN', name: 'Titan Company', weight: 8, type: 'Stock' },
      { symbol: 'ZOMATO', name: 'Zomato', weight: 8, type: 'Stock' },
      { symbol: 'DIVISLAB', name: 'Divis Labs', weight: 7, type: 'Stock' },
      { symbol: 'JIOFIN', name: 'Jio Financial', weight: 7, type: 'Stock' },
      { symbol: 'PERSISTENT', name: 'Persistent Systems', weight: 7, type: 'Stock' },
      { symbol: 'TRENT', name: 'Trent', weight: 6, type: 'Stock' },
      { symbol: 'VBL', name: 'Varun Beverages', weight: 7, type: 'Stock' },
    ],
    methodology: 'Top 12 momentum stocks from NSE 500 universe, ranked by 12-1 month price momentum, rebalanced monthly with volatility filter.',
    published: true,
  },
  {
    id: 'dividend-aristocrats',
    name: 'Dividend Aristocrats',
    subtitle: 'Steady payers with growing dividend history',
    managerId: 'northstar',
    volatility: 'Low', risk: 'Low', strategy: 'model-based',
    themes: ['Dividend'], sectors: [], goals: ['Regular income'], assetType: 'Equity',
    returns: makeReturns(0.8, 5.1, 11.4, 14.9, 13.2, 12.4),
    minAmount: 6200, horizon: 'Long term (5y+)', rebalanceFreq: 'Semi-annual',
    lastRebalancedAt: '2025-04-15', fee: { type: 'free', amount: 0, cycle: null }, subscription: 'Free',
    constituents: [
      { symbol: 'ITC', name: 'ITC', weight: 12, type: 'Stock' },
      { symbol: 'COALINDIA', name: 'Coal India', weight: 12, type: 'Stock' },
      { symbol: 'HINDPETRO', name: 'Hindustan Petroleum', weight: 10, type: 'Stock' },
      { symbol: 'POWERGRID', name: 'Power Grid', weight: 10, type: 'Stock' },
      { symbol: 'IOC', name: 'Indian Oil', weight: 10, type: 'Stock' },
      { symbol: 'NTPC', name: 'NTPC', weight: 10, type: 'Stock' },
      { symbol: 'ONGC', name: 'ONGC', weight: 10, type: 'Stock' },
      { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp', weight: 9, type: 'Stock' },
      { symbol: 'INFY', name: 'Infosys', weight: 9, type: 'Stock' },
      { symbol: 'HCLTECH', name: 'HCL Tech', weight: 8, type: 'Stock' },
    ],
    methodology: 'Companies with 10+ years of consistent dividend growth and payout ratio above 40%.',
    published: true,
  },
  {
    id: 'tech-titans',
    name: 'Tech Titans',
    subtitle: 'Leaders of Indian & global technology',
    managerId: 'windmill',
    volatility: 'High', risk: 'High', strategy: 'sectoral',
    themes: ['IT & Tech'], sectors: ['IT'], goals: ['Wealth creation'], assetType: 'Equity',
    returns: makeReturns(2.1, 11.3, 22.8, 26.7, 23.1, 21.6),
    minAmount: 15400, horizon: 'Long term (5y+)', rebalanceFreq: 'Quarterly',
    lastRebalancedAt: '2025-06-30', fee: { type: 'subscription', amount: 499, cycle: 'quarterly' }, subscription: 'Paid',
    constituents: [
      { symbol: 'TCS', name: 'Tata Consultancy', weight: 18, type: 'Stock' },
      { symbol: 'INFY', name: 'Infosys', weight: 16, type: 'Stock' },
      { symbol: 'HCLTECH', name: 'HCL Technologies', weight: 12, type: 'Stock' },
      { symbol: 'WIPRO', name: 'Wipro', weight: 10, type: 'Stock' },
      { symbol: 'TECHM', name: 'Tech Mahindra', weight: 10, type: 'Stock' },
      { symbol: 'LTIM', name: 'LTIMindtree', weight: 9, type: 'Stock' },
      { symbol: 'PERSISTENT', name: 'Persistent Systems', weight: 9, type: 'Stock' },
      { symbol: 'MPHASIS', name: 'Mphasis', weight: 8, type: 'Stock' },
      { symbol: 'COFORGE', name: 'Coforge', weight: 8, type: 'Stock' },
    ],
    methodology: 'Market-cap weighted portfolio of top Indian IT services and product companies with international revenue exposure.',
    published: true,
  },
  {
    id: 'green-energy',
    name: 'Green Energy Rising',
    subtitle: 'Solar, wind, EV, and clean-tech leaders',
    managerId: 'niveshaay',
    volatility: 'Medium', risk: 'Medium', strategy: 'thematic',
    themes: ['Green Energy', 'ESG'], sectors: ['Energy'], goals: ['Wealth creation'], assetType: 'Equity',
    returns: makeReturns(1.6, 9.4, 19.8, 22.1, 17.4, 16.2),
    minAmount: 9800, horizon: 'Long term (5y+)', rebalanceFreq: 'Quarterly',
    lastRebalancedAt: '2025-06-05', fee: { type: 'subscription', amount: 299, cycle: 'monthly' }, subscription: 'Paid',
    constituents: [
      { symbol: 'ADANIGREEN', name: 'Adani Green', weight: 15, type: 'Stock' },
      { symbol: 'TATAPOWER', name: 'Tata Power', weight: 14, type: 'Stock' },
      { symbol: 'JSWENERGY', name: 'JSW Energy', weight: 12, type: 'Stock' },
      { symbol: 'NHPC', name: 'NHPC', weight: 10, type: 'Stock' },
      { symbol: 'SUZLON', name: 'Suzlon Energy', weight: 10, type: 'Stock' },
      { symbol: 'INOXWIND', name: 'Inox Wind', weight: 10, type: 'Stock' },
      { symbol: 'OLECTRA', name: 'Olectra Greentech', weight: 10, type: 'Stock' },
      { symbol: 'BOROSIL', name: 'Borosil Renewables', weight: 10, type: 'Stock' },
      { symbol: 'KPI', name: 'KPI Green Energy', weight: 9, type: 'Stock' },
    ],
    methodology: 'Pure-play clean energy names across renewable generation, EV, and green infrastructure.',
    published: true,
  },
  {
    id: 'banking-leaders',
    name: 'Banking Leaders',
    subtitle: 'The strongest private and public sector banks',
    managerId: 'northstar',
    volatility: 'Medium', risk: 'Medium', strategy: 'sectoral',
    themes: [], sectors: ['Banking'], goals: ['Wealth creation'], assetType: 'Equity',
    returns: makeReturns(1.4, 7.9, 16.2, 19.6, 15.8, 14.9),
    minAmount: 11200, horizon: 'Long term (5y+)', rebalanceFreq: 'Quarterly',
    lastRebalancedAt: '2025-06-20', fee: { type: 'free', amount: 0, cycle: null }, subscription: 'Free',
    constituents: [
      { symbol: 'HDFCBANK', name: 'HDFC Bank', weight: 22, type: 'Stock' },
      { symbol: 'ICICIBANK', name: 'ICICI Bank', weight: 20, type: 'Stock' },
      { symbol: 'SBIN', name: 'State Bank of India', weight: 15, type: 'Stock' },
      { symbol: 'AXISBANK', name: 'Axis Bank', weight: 13, type: 'Stock' },
      { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank', weight: 12, type: 'Stock' },
      { symbol: 'INDUSINDBK', name: 'IndusInd Bank', weight: 8, type: 'Stock' },
      { symbol: 'BANDHANBNK', name: 'Bandhan Bank', weight: 5, type: 'Stock' },
      { symbol: 'FEDERALBNK', name: 'Federal Bank', weight: 5, type: 'Stock' },
    ],
    methodology: 'Top scheduled commercial banks by market cap, blend of private and PSU, weighted by profitability and asset quality.',
    published: true,
  },
  {
    id: 'ev-revolution',
    name: 'Electric Vehicle Revolution',
    subtitle: 'India\'s EV supply chain from lithium to leasing',
    managerId: 'niveshaay',
    volatility: 'High', risk: 'High', strategy: 'thematic',
    themes: ['Electric Vehicles', 'Make in India'], sectors: ['Auto'], goals: ['Wealth creation'], assetType: 'Equity',
    returns: makeReturns(2.6, 12.1, 24.4, 27.9, 21.3, 19.8),
    minAmount: 14200, horizon: 'Long term (5y+)', rebalanceFreq: 'Quarterly',
    lastRebalancedAt: '2025-06-18', fee: { type: 'subscription', amount: 349, cycle: 'monthly' }, subscription: 'Paid',
    constituents: [
      { symbol: 'TATAMOTORS', name: 'Tata Motors', weight: 14, type: 'Stock' },
      { symbol: 'M&M', name: 'Mahindra & Mahindra', weight: 12, type: 'Stock' },
      { symbol: 'EXIDEIND', name: 'Exide Industries', weight: 11, type: 'Stock' },
      { symbol: 'AMARAJABAT', name: 'Amara Raja', weight: 10, type: 'Stock' },
      { symbol: 'OLECTRA', name: 'Olectra Greentech', weight: 10, type: 'Stock' },
      { symbol: 'GREAVESCOT', name: 'Greaves Cotton', weight: 9, type: 'Stock' },
      { symbol: 'JBMA', name: 'JBM Auto', weight: 9, type: 'Stock' },
      { symbol: 'HIMADRI', name: 'Himadri Speciality', weight: 9, type: 'Stock' },
      { symbol: 'MOTHERSON', name: 'Samvardhana Motherson', weight: 8, type: 'Stock' },
      { symbol: 'BHEL', name: 'BHEL', weight: 8, type: 'Stock' },
    ],
    methodology: 'Companies with meaningful EV or EV-supply-chain revenue exposure across OEMs, batteries, charging, and components.',
    published: true,
  },
  {
    id: 'value-investing',
    name: 'Value Investors',
    subtitle: 'Quality companies trading below intrinsic value',
    managerId: 'omniscience',
    volatility: 'Medium', risk: 'Medium', strategy: 'model-based',
    themes: ['Value'], sectors: [], goals: ['Wealth creation'], assetType: 'Equity',
    returns: makeReturns(0.9, 6.1, 14.2, 17.8, 14.6, 13.9),
    minAmount: 7500, horizon: 'Long term (5y+)', rebalanceFreq: 'Semi-annual',
    lastRebalancedAt: '2025-05-01', fee: { type: 'subscription', amount: 149, cycle: 'monthly' }, subscription: 'Paid',
    constituents: [
      { symbol: 'ITC', name: 'ITC', weight: 10, type: 'Stock' },
      { symbol: 'COALINDIA', name: 'Coal India', weight: 10, type: 'Stock' },
      { symbol: 'ONGC', name: 'ONGC', weight: 10, type: 'Stock' },
      { symbol: 'NTPC', name: 'NTPC', weight: 10, type: 'Stock' },
      { symbol: 'HINDPETRO', name: 'HPCL', weight: 10, type: 'Stock' },
      { symbol: 'BPCL', name: 'BPCL', weight: 10, type: 'Stock' },
      { symbol: 'SAIL', name: 'Steel Authority', weight: 10, type: 'Stock' },
      { symbol: 'GAIL', name: 'GAIL India', weight: 10, type: 'Stock' },
      { symbol: 'NMDC', name: 'NMDC', weight: 10, type: 'Stock' },
      { symbol: 'REC', name: 'REC Ltd', weight: 10, type: 'Stock' },
    ],
    methodology: 'Companies ranked on P/E, P/B, EV/EBITDA vs sector medians with positive earnings growth.',
    published: true,
  },
  {
    id: 'pharma-plus',
    name: 'Pharma Plus',
    subtitle: 'India\'s pharmaceutical and healthcare leaders',
    managerId: 'northstar',
    volatility: 'Medium', risk: 'Medium', strategy: 'sectoral',
    themes: [], sectors: ['Pharma'], goals: ['Wealth creation'], assetType: 'Equity',
    returns: makeReturns(1.1, 8.4, 17.2, 20.4, 16.3, 15.1),
    minAmount: 10500, horizon: 'Long term (5y+)', rebalanceFreq: 'Quarterly',
    lastRebalancedAt: '2025-06-22', fee: { type: 'free', amount: 0, cycle: null }, subscription: 'Free',
    constituents: [
      { symbol: 'SUNPHARMA', name: 'Sun Pharma', weight: 18, type: 'Stock' },
      { symbol: 'CIPLA', name: 'Cipla', weight: 14, type: 'Stock' },
      { symbol: 'DIVISLAB', name: 'Divis Labs', weight: 12, type: 'Stock' },
      { symbol: 'DRREDDY', name: 'Dr Reddy\'s', weight: 12, type: 'Stock' },
      { symbol: 'LUPIN', name: 'Lupin', weight: 10, type: 'Stock' },
      { symbol: 'AUROPHARMA', name: 'Aurobindo Pharma', weight: 9, type: 'Stock' },
      { symbol: 'TORNTPHARM', name: 'Torrent Pharma', weight: 9, type: 'Stock' },
      { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals', weight: 8, type: 'Stock' },
      { symbol: 'BIOCON', name: 'Biocon', weight: 8, type: 'Stock' },
    ],
    methodology: 'Large & mid cap pharma and healthcare businesses with strong R&D pipeline.',
    published: true,
  },
  {
    id: 'weekend-momentum',
    name: 'Weekend Momentum',
    subtitle: 'A weekly rebalanced momentum machine',
    managerId: 'weekend',
    volatility: 'High', risk: 'High', strategy: 'model-based',
    themes: ['Momentum'], sectors: [], goals: ['Wealth creation'], assetType: 'Equity',
    returns: makeReturns(4.1, 15.7, 32.1, 34.6, 28.4, 26.1),
    minAmount: 18000, horizon: 'Medium term (3-5y)', rebalanceFreq: 'Weekly',
    lastRebalancedAt: '2025-07-08', fee: { type: 'subscription', amount: 799, cycle: 'monthly' }, subscription: 'Paid',
    constituents: [
      { symbol: 'BEL', name: 'Bharat Electronics', weight: 8, type: 'Stock' },
      { symbol: 'CDSL', name: 'CDSL', weight: 8, type: 'Stock' },
      { symbol: 'BSE', name: 'BSE', weight: 8, type: 'Stock' },
      { symbol: 'RVNL', name: 'Rail Vikas Nigam', weight: 8, type: 'Stock' },
      { symbol: 'IRCON', name: 'IRCON International', weight: 8, type: 'Stock' },
      { symbol: 'GRSE', name: 'Garden Reach Ship', weight: 8, type: 'Stock' },
      { symbol: 'MAZDOCK', name: 'Mazagon Dock', weight: 8, type: 'Stock' },
      { symbol: 'HAL', name: 'Hindustan Aeronautics', weight: 8, type: 'Stock' },
      { symbol: 'ANGELONE', name: 'Angel One', weight: 7, type: 'Stock' },
      { symbol: 'CAMS', name: 'CAMS', weight: 7, type: 'Stock' },
      { symbol: 'PPLPHARMA', name: 'PPL Pharma', weight: 7, type: 'Stock' },
      { symbol: 'IREDA', name: 'IREDA', weight: 7, type: 'Stock' },
      { symbol: 'NLC', name: 'NLC India', weight: 8, type: 'Stock' },
    ],
    methodology: 'Top 13 momentum names on weekly re-rank, with strict volatility and liquidity screens.',
    published: true,
  },
  {
    id: 'consumption-story',
    name: 'India Consumption Story',
    subtitle: 'Riding the rise of the Indian consumer',
    managerId: 'niveshaay',
    volatility: 'Medium', risk: 'Medium', strategy: 'thematic',
    themes: ['Consumption'], sectors: ['FMCG'], goals: ['Wealth creation'], assetType: 'Equity',
    returns: makeReturns(1.0, 6.9, 15.8, 18.9, 15.4, 14.2),
    minAmount: 8900, horizon: 'Long term (5y+)', rebalanceFreq: 'Quarterly',
    lastRebalancedAt: '2025-06-10', fee: { type: 'subscription', amount: 199, cycle: 'monthly' }, subscription: 'Paid',
    constituents: [
      { symbol: 'HINDUNILVR', name: 'Hindustan Unilever', weight: 14, type: 'Stock' },
      { symbol: 'ITC', name: 'ITC', weight: 12, type: 'Stock' },
      { symbol: 'NESTLEIND', name: 'Nestle India', weight: 11, type: 'Stock' },
      { symbol: 'BRITANNIA', name: 'Britannia', weight: 10, type: 'Stock' },
      { symbol: 'DABUR', name: 'Dabur', weight: 9, type: 'Stock' },
      { symbol: 'MARICO', name: 'Marico', weight: 9, type: 'Stock' },
      { symbol: 'TITAN', name: 'Titan', weight: 9, type: 'Stock' },
      { symbol: 'TRENT', name: 'Trent', weight: 9, type: 'Stock' },
      { symbol: 'ASIANPAINT', name: 'Asian Paints', weight: 9, type: 'Stock' },
      { symbol: 'VBL', name: 'Varun Beverages', weight: 8, type: 'Stock' },
    ],
    methodology: 'Consumer discretionary and staples brands with strong pricing power and rural + urban distribution.',
    published: true,
  },
  {
    id: 'smart-beta-quality',
    name: 'Smart Beta Quality',
    subtitle: 'High-ROE, low-debt compounders',
    managerId: 'omniscience',
    volatility: 'Low', risk: 'Low', strategy: 'smart-beta',
    themes: ['Quality'], sectors: [], goals: ['Wealth creation'], assetType: 'Equity',
    returns: makeReturns(0.9, 5.7, 13.4, 16.2, 14.1, 13.1),
    minAmount: 7100, horizon: 'Long term (5y+)', rebalanceFreq: 'Semi-annual',
    lastRebalancedAt: '2025-04-25', fee: { type: 'free', amount: 0, cycle: null }, subscription: 'Free',
    constituents: [
      { symbol: 'TCS', name: 'TCS', weight: 12, type: 'Stock' },
      { symbol: 'HDFCBANK', name: 'HDFC Bank', weight: 11, type: 'Stock' },
      { symbol: 'ASIANPAINT', name: 'Asian Paints', weight: 10, type: 'Stock' },
      { symbol: 'HINDUNILVR', name: 'HUL', weight: 10, type: 'Stock' },
      { symbol: 'NESTLEIND', name: 'Nestle India', weight: 10, type: 'Stock' },
      { symbol: 'PIDILITIND', name: 'Pidilite', weight: 10, type: 'Stock' },
      { symbol: 'BAJFINANCE', name: 'Bajaj Finance', weight: 9, type: 'Stock' },
      { symbol: 'MARICO', name: 'Marico', weight: 9, type: 'Stock' },
      { symbol: 'BRITANNIA', name: 'Britannia', weight: 9, type: 'Stock' },
      { symbol: 'DIVISLAB', name: 'Divis Labs', weight: 10, type: 'Stock' },
    ],
    methodology: 'Companies scoring in the top decile on ROE, low leverage, and stable earnings growth over 5 years.',
    published: true,
  },
];

// helpers
export const getManager = (id) => managers.find(m => m.id === id);
export const getBasket = (id) => baskets.find(b => b.id === id);

// Generate a mock performance curve for each basket
export const generatePerformance = (basketId, months = 60) => {
  const b = getBasket(basketId);
  const cagr = b ? b.returns.cagr / 100 : 0.15;
  const points = [];
  let value = 100;
  const monthly = Math.pow(1 + cagr, 1/12) - 1;
  const now = new Date();
  for (let i = months; i >= 0; i--) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    // add pseudo random noise deterministic by basketId+i
    const seed = (basketId.charCodeAt(0) + i) % 17;
    const noise = (Math.sin(seed * 0.7) * 0.04);
    value = value * (1 + monthly + noise);
    points.push({ date: d.toISOString().slice(0,7), value: Number(value.toFixed(2)) });
  }
  return points;
};

export const collections = [
  { id: 'ipo-winners', slug: 'ipo-winners', title: 'IPO Winners', type: 'stock', description: 'Recent listings with strong fundamentals', icon: 'Sparkles' },
  { id: 'nifty-index', slug: 'nifty-index-funds', title: 'Nifty 50 Index Funds', type: 'mf', description: 'Passive funds tracking Nifty 50', icon: 'LineChart' },
  { id: 'monthly-income', slug: 'monthly-income', title: 'Monthly Income Funds', type: 'mf', description: 'Debt-oriented funds paying monthly', icon: 'Coins' },
  { id: 'blue-chip-stocks', slug: 'blue-chip-stocks', title: 'Blue Chip Stocks', type: 'stock', description: 'Large, established, dividend-paying leaders', icon: 'Award' },
  { id: 'high-growth', slug: 'high-growth-stocks', title: 'High Growth Stocks', type: 'stock', description: 'Fast growing mid & small cap names', icon: 'TrendingUp' },
  { id: 'best-10y', slug: 'best-10y-funds', title: 'Best-performing 10Y funds', type: 'mf', description: 'MFs with the strongest decade-long returns', icon: 'Medal' },
  { id: 'low-expense', slug: 'low-expense-funds', title: 'Low expense-ratio funds', type: 'mf', description: 'Funds with expense ratio below 0.5%', icon: 'PiggyBank' },
  { id: 'sip-friendly', slug: 'sip-friendly-funds', title: 'SIP-friendly funds', type: 'mf', description: 'Best funds for monthly SIPs', icon: 'CalendarClock' },
];

export const mutualFunds = [
  { id: 'axis-bluechip', name: 'Axis Bluechip Fund', category: 'equity', amc: 'Axis MF', nav: 68.42, returns: { y1: 18.2, y3: 15.4, y5: 14.1 }, expenseRatio: 0.52 },
  { id: 'parag-flexi', name: 'Parag Parikh Flexi Cap', category: 'equity', amc: 'PPFAS', nav: 82.16, returns: { y1: 22.8, y3: 21.4, y5: 19.6 }, expenseRatio: 0.66 },
  { id: 'hdfc-mid', name: 'HDFC Mid-Cap Opportunities', category: 'equity', amc: 'HDFC MF', nav: 172.34, returns: { y1: 31.4, y3: 28.1, y5: 22.6 }, expenseRatio: 0.72 },
  { id: 'mirae-large', name: 'Mirae Asset Large Cap', category: 'equity', amc: 'Mirae', nav: 105.67, returns: { y1: 16.8, y3: 14.9, y5: 13.4 }, expenseRatio: 0.54 },
  { id: 'sbi-small', name: 'SBI Small Cap Fund', category: 'equity', amc: 'SBI MF', nav: 148.90, returns: { y1: 34.2, y3: 29.6, y5: 24.1 }, expenseRatio: 0.71 },
  { id: 'icici-corp', name: 'ICICI Corporate Bond', category: 'debt', amc: 'ICICI Pru', nav: 27.42, returns: { y1: 7.8, y3: 6.9, y5: 7.2 }, expenseRatio: 0.34 },
  { id: 'hdfc-shortterm', name: 'HDFC Short Term Debt', category: 'debt', amc: 'HDFC MF', nav: 29.11, returns: { y1: 7.2, y3: 6.6, y5: 7.1 }, expenseRatio: 0.31 },
  { id: 'sbi-liquid', name: 'SBI Liquid Fund', category: 'debt', amc: 'SBI MF', nav: 3742.10, returns: { y1: 6.9, y3: 5.8, y5: 5.9 }, expenseRatio: 0.19 },
  { id: 'icici-balanced', name: 'ICICI Prudential Balanced Advantage', category: 'hybrid', amc: 'ICICI Pru', nav: 62.45, returns: { y1: 14.2, y3: 12.6, y5: 12.1 }, expenseRatio: 0.62 },
  { id: 'hdfc-hybrid', name: 'HDFC Hybrid Equity', category: 'hybrid', amc: 'HDFC MF', nav: 89.21, returns: { y1: 15.4, y3: 13.8, y5: 13.2 }, expenseRatio: 0.58 },
  { id: 'gold-fund', name: 'Nippon India Gold Fund', category: 'other', amc: 'Nippon', nav: 24.11, returns: { y1: 22.4, y3: 15.6, y5: 13.9 }, expenseRatio: 0.35 },
  { id: 'intl-fund', name: 'Motilal Oswal Nasdaq 100', category: 'other', amc: 'Motilal', nav: 194.56, returns: { y1: 28.1, y3: 22.4, y5: 19.8 }, expenseRatio: 0.41 },
];

export const fixedDeposits = [
  { id: 'shriram', provider: 'Shriram Finance', rate: 9.20, tenure: '36 months', insured: false, minAmount: 5000 },
  { id: 'bajaj', provider: 'Bajaj Finance', rate: 8.65, tenure: '44 months', insured: false, minAmount: 15000 },
  { id: 'mahindra', provider: 'Mahindra Finance', rate: 8.30, tenure: '36 months', insured: false, minAmount: 5000 },
  { id: 'sbi', provider: 'State Bank of India', rate: 7.00, tenure: '5 years', insured: true, minAmount: 1000 },
  { id: 'hdfc-bank', provider: 'HDFC Bank', rate: 7.25, tenure: '5 years', insured: true, minAmount: 5000 },
  { id: 'icici-bank', provider: 'ICICI Bank', rate: 7.20, tenure: '5 years', insured: true, minAmount: 10000 },
  { id: 'aubank', provider: 'AU Small Finance Bank', rate: 8.00, tenure: '3 years', insured: true, minAmount: 5000 },
  { id: 'ujjivan', provider: 'Ujjivan Small Finance', rate: 8.25, tenure: '3 years', insured: true, minAmount: 1000 },
];

export const testimonials = [
  { name: 'Ananya R.', initial: 'A', tag: 'Investor, 2 yrs', quote: 'I finally stopped guessing which stocks to buy. Picked a basket, connected my broker, done.' },
  { name: 'Vikram S.', initial: 'V', tag: 'Investor, 4 yrs', quote: 'The rebalancing nudges are gold. One tap and my portfolio stays aligned to the strategy.' },
  { name: 'Meera K.', initial: 'M', tag: 'Investor, 1 yr', quote: 'Everything is transparent — every holding and fee is right there before I commit a rupee.' },
];

export const faqs = [
  { q: 'Where are my stocks held?', a: 'Every share you buy sits in your own demat account with your broker. Omnivest never holds your money or securities.' },
  { q: 'How much does it cost?', a: 'A small transaction fee per order, shown before you invest, plus a manager subscription on premium baskets. Standard broker charges apply on trades.' },
  { q: 'Can I exit anytime?', a: 'Yes. You can sell part or all of any basket whenever you like, directly from your dashboard.' },
  { q: 'What is rebalancing?', a: 'When a basket\'s strategy changes, the manager updates its holdings. You get a notification and can apply the update in one tap.' },
  { q: 'Is there a minimum lock-in?', a: 'No. There is no lock-in on baskets. Sell whenever you like, subject to standard settlement cycles.' },
  { q: 'How is a basket different from a mutual fund?', a: 'You directly own the underlying shares in your demat account, get full transparency into holdings, and can customise weights.' },
];

export const learnPosts = [
  { slug: 'what-is-a-basket', title: 'What is a curated basket, really?', category: 'Basics', excerpt: 'A basket is a portfolio built around one idea. Here is how it works.', thumbnail: 'gradient-1', readTime: '4 min read' },
  { slug: 'how-rebalancing-works', title: 'How rebalancing keeps your portfolio on strategy', category: 'How it works', excerpt: 'When the manager updates weights, you apply it in one tap.', thumbnail: 'gradient-2', readTime: '3 min read' },
  { slug: 'sip-vs-lumpsum', title: 'SIP vs lumpsum: which one wins over 10 years?', category: 'Strategy', excerpt: 'The evidence is more nuanced than most people think.', thumbnail: 'gradient-3', readTime: '6 min read' },
  { slug: 'reading-a-factsheet', title: 'How to read a basket factsheet like a pro', category: 'Basics', excerpt: 'What each metric tells you and what it hides.', thumbnail: 'gradient-4', readTime: '5 min read' },
  { slug: 'goal-based-investing', title: 'Goal-based investing 101', category: 'Strategy', excerpt: 'From house down payment to retirement, tie every rupee to a goal.', thumbnail: 'gradient-5', readTime: '7 min read' },
  { slug: 'risk-and-volatility', title: 'Risk vs volatility: they are not the same', category: 'Basics', excerpt: 'Understanding what actually threatens your capital.', thumbnail: 'gradient-6', readTime: '4 min read' },
];

export const stocks = [
  { symbol: 'RELIANCE', name: 'Reliance Industries', marketCap: 'Large Cap', price: 2984.20, sector: 'Energy', change: 1.2 },
  { symbol: 'TCS', name: 'Tata Consultancy Services', marketCap: 'Large Cap', price: 3892.60, sector: 'IT', change: -0.4 },
  { symbol: 'HDFCBANK', name: 'HDFC Bank', marketCap: 'Large Cap', price: 1642.30, sector: 'Banking', change: 0.8 },
  { symbol: 'INFY', name: 'Infosys', marketCap: 'Large Cap', price: 1841.90, sector: 'IT', change: -0.2 },
  { symbol: 'ITC', name: 'ITC Limited', marketCap: 'Large Cap', price: 462.75, sector: 'FMCG', change: 0.6 },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance', marketCap: 'Large Cap', price: 7124.60, sector: 'NBFC', change: 2.1 },
  { symbol: 'TATAMOTORS', name: 'Tata Motors', marketCap: 'Large Cap', price: 942.10, sector: 'Auto', change: 1.7 },
  { symbol: 'ADANIENT', name: 'Adani Enterprises', marketCap: 'Large Cap', price: 3184.50, sector: 'Diversified', change: -1.4 },
  { symbol: 'ZOMATO', name: 'Zomato', marketCap: 'Mid Cap', price: 264.30, sector: 'Consumer Tech', change: 3.2 },
  { symbol: 'PERSISTENT', name: 'Persistent Systems', marketCap: 'Mid Cap', price: 5842.10, sector: 'IT', change: 1.8 },
  { symbol: 'PAYTM', name: 'Paytm (One97 Comm.)', marketCap: 'Mid Cap', price: 468.20, sector: 'Fintech', change: -2.6 },
  { symbol: 'IREDA', name: 'IREDA', marketCap: 'Mid Cap', price: 214.60, sector: 'Financials', change: 4.1 },
];
